### ISSUE TITLE
[C4 Finding] Hook deployment is vulnerable to reorg situations

### ISSUE THREAD

**Issue by d1ll0n** [wildcat-finance/v2-protocol#44]
Finding: [Hook deployment is vulnerable to reorg situations](https://github.com/code-423n4/2024-08-wildcat-findings/issues/36)

The issue is that the hooks instance addresses are derived solely from the contract nonce, so if there are reorgs on sidechains and multiple people had deployed in the same time period, the instance addresses could be swapped if the transactions are reordered. Low impact but worth addressing.

**Solution:** Use Create2 to deploy hooks instances, with salt derived from sender address and a partial salt provided by the caller (same as market salt derivation).

**Comment by laurenceday** [comment]
Fixed by https://github.com/wildcat-finance/v2-protocol/commit/1a52863b27180f33c5055f8d95306a4471577d86
