### ISSUE TITLE
Contract SPDX identifier does not indicate use of Commons Clause

### ISSUE THREAD

**Issue by TimTinkers** [wildcat-finance/v2-protocol#68]
The [Wildcat license](https://github.com/wildcat-finance/v2-protocol/blob/main/LICENSE.md) is Apache 2.0 modified by the [Commons Clause](https://commonsclause.com/). This is not reflected in the SPDX license identifiers of the smart contracts themselves, which give the impression from reading the contracts alone that Wildcat is proper Free Software.

**Comment by laurenceday** [comment]
Merged with thanks
